### PR TITLE
Fix and refactor logic for no results

### PR DESCRIPTION
**Pull request by mirhamasala**
https://howican.atlassian.net/browse/PER-4

### CODE REVIEW

**Comment by shiolovesgod** [comment]
Hi @mirhamasala, 

Great work!

Would you mind adding a link to the Jira issue and the acceptance criteria in the description section of your pull request? 

I'm not sure which PER tasks this stems from.

**Comment by mirhamasala** [comment]
@reneefromhold, I'm looking into this right now. And there's one thing I noticed with this workflow.

If a user searches for a query that doesn't match any articles, then the suggestions will be empty. So the suggestions will be empty, the articles remain the same in the background, but she won't know that there are no results for her query until she hits enter ..

**Comment by reneefromhold** [comment]
@mirhamasala Can the 0 result display in that case, where the user does not hit enter but no suggestions exist? What we want to avoid, if possible, is going through the work of updating the cards if the user has not confirmed (by way of hitting enter or search icon) that the search phrase entered is complete.

**Comment by mirhamasala** [comment]
@reneefromhold I fixed the code to do as we discussed. When there are no search results, the `NoResults` component shows, and the default `NewsCards` don't.

**Comment by mirhamasala** [comment]
When the user hits enter, the news cards now also populate with the user's query.

**Pull request merged**
